### ISSUE TITLE
Powerplan "auto" wrongly detects powersource status

### ISSUE THREAD

**Issue by jambt** [pyamsoft/pstate-frequency#18]
After issuing a

`# pstate-frequency -S -p 0` (auto)

my values are set as if the power source were not connected (Turbo OFF, governor: powersave). Although the powersource is connected.

Manully specifying `pstate-frequency -S -g performance` and `pstate-frequency -S -t 0` sets the desired values.

This happens with a Lenovo Thinkpad X250 which is docked into an UltraDock Docking Station (with power cord attached).

**Comment by pyamsoft** [comment]
Please run a couple of commands for me. First set the performance plan, 2.

    pstate-frequency -S -p 2

This should set your values to the following

MAX = 100
MIN = <your CPU minimum>
TURBO = OFF
GOVERNOR = POWERSAVE

The auto plan runs this plan when connected to a power source. If these values are the same as what you are seeing when running the auto plan, them this is actually working as intended. If you wish for the auto plan to instead set a max-performance plan which enables TURBO and sets the governor to PERFORMANCE, then I can patch that in as an option.

**Comment by jambt** [comment]
Thank you very much for clearing that up. I indeed mixed up the performance plan (2) and the max-performance plan (3). So this is my fault. Turbo is supposed to be off, so my results are consistent with the intended behaviour and there is no issue here.

Nevertheless, thank you for offering to build in different default values! If this is easy to do, I would appreciate it. If not, then please excuse my error and thank you again for your quick help!
