### ISSUE TITLE
Permission error in /sys/devices/system/cpu/cpufreq/boost

### ISSUE THREAD

**Issue by diegobersanetti** [pyamsoft/pstate-frequency#29]
Hello,
I updated pstate-frequency to the last version 3.7.0; now when I manually change the policy, for example with the command

sudo /path/pstate-frequency -S -g powersave -t off

I receive the following error:

/path/pstate-frequency: 1303: /path/pstate-frequency: cannot create /sys/devices/system/cpu/cpufreq/boost: Permission denied

I looked into that folder, and there is no 'boost' directory, nor I can create it even with sudo.

I am on Ubuntu 16.04, with an Haswell processor and the intel_pstate governor. I did not install service units, nor udev rules, I just run pstate-frequency manually because to change settings on the fly, the automatic switch w.r.t. battery state is done by TLP.

Regards,

Diego

**Comment by ozky** [comment]
Seems to be sudo problem as in Mageia 6 it works with full root permission out of box.
Have you try to use sudo -i in terminal ? it will give root priviledges and then try to call pstate command.
`[root@ozky-pc ~]# pstate-frequency -S -g powersave -t off
pstate-frequency version 3.6.3
    pstate::CPU_DRIVER   -> intel_pstate
    pstate::CPU_GOVERNOR -> powersave
    pstate::TURBO        -> 1 [OFF]
    pstate::CPU_MIN      -> 19% [499800KHz]
    pstate::CPU_MAX      -> 100% [2582300KHz] `

**Comment by diegobersanetti** [comment]
Unfortunately nothing changes...

I noticed "cpufreq" in the path of the error, which seems weird to me as I'm not using cpufreq as governor... Moreover, looking at the '/sys/devices/system/cpu/cpufreq' folder, the only folders in there are 'policy0' to 'policy7'

**Comment by pyamsoft** [comment]
Hi there, sorry to hear of the issue you're experiencing. Never seen this one myself personally, but let's get to the root of it.

Please tell me the following:
Kernel version
Whether you are using acpi-cpufreq or intel_pstate

Try using the very recently released 3.7.1 version and let me know if that fixes your issue. Thanks!

**Comment by diegobersanetti** [comment]
Hello,
I tried the new version 3.7.1 and the problem went away, thank you!

I use Ubuntu 16.04.1 with kernel 4.4.0-53-generic, and intel_pstate; now pstate-frequency finds the right place for the boost information!

Thanks again for the fix and your work on pstate-frequency!

Diego

**Comment by pyamsoft** [comment]
Thank you for the report.

I will close this ticket as the issue has been resolved.
