### ISSUE TITLE
Can't set a frequency

### ISSUE THREAD

**Issue by Mistrotech** [pyamsoft/pstate-frequency#41]
When I type "sudo pstate-frequency --set <50%>" into the terminal, it returns "bash: syntax error near unexpected token `newline'." Am I not correctly writing out the code? Perhaps write how to type the code exactly in the README file.

Thanks in advance.

**Comment by pyamsoft** [comment]
Hi

So there are two things that need to be adjusted

First is, you don't need to include a percentage sign, just `50` is enough. 

Second you need to specify what you are setting to 50, the --min or --max CPU frequency

Something like

`sudo pstate-frequency --set --max 50`
