### ISSUE TITLE
ERROR: pstate-frequency is not supported on your system.

### ISSUE THREAD

**Issue by lostsoul6** [pyamsoft/pstate-frequency#45]
Hi there ,

I use Ubuntu 22 server on a VMware VPS and I get "ERROR: pstate-frequency is not supported on your system" while running pstate-frequency command . what does that mean ? Why aren't I able to use it ?

**Comment by pyamsoft** [comment]
Hi, on a VPS you won't have access to the underlying sysfs so there is no CPU driver to control.
